[tool.black]
line-length = 88
target-version = ["py313"]

[tool.ruff]
line-length = 88
target-version = "py313"
src = ["app"]

[tool.ruff.format]
preview = false

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "I",  # import sorting
    "UP",  # pyupgrade
    "RUF",  # Ruff-specific rules
]
ignore = []
fixable = ["ALL"]
