export const styles = {
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  headerShell: {
    display: "flex",
    alignItems: "stretch",
    gap: 16,
    marginBottom: 18,
  },
  pageLayout: {
    display: "flex",
    alignItems: "flex-start",
    gap: 16,
  },
  pageContent: {
    flex: 1,
    minWidth: 0,
  },
  headerMain: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  headerTopRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  headerRight: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  sideMenu: {
    width: 220,
    padding: 14,
    borderRadius: 16,
    background: "rgba(15,23,42,0.7)",
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "0 18px 40px rgba(0,0,0,0.3)",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  sideMenuCollapsed: {
    width: 72,
    padding: 12,
  },
  sideMenuGroup: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sideMenuButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(30,41,59,0.6)",
    color: "#e2e8f0",
    cursor: "pointer",
    textAlign: "left",
  },
  sideMenuButtonCollapsed: {
    justifyContent: "center",
    padding: "10px",
  },
  sideMenuIcon: {
    width: 24,
    height: 24,
    borderRadius: 8,
    background: "rgba(255,255,255,0.08)",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
  },
  sideMenuLabel: {
    whiteSpace: "nowrap",
  },
  sideMenuLabelCollapsed: {
    display: "none",
  },
  sideMenuToggle: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(15,23,42,0.75)",
    color: "#e2e8f0",
    cursor: "pointer",
    textAlign: "left",
  },
  sideMenuItemWrapper: {
    position: "relative",
    width: "100%",
  },
  searchInput: {
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    minWidth: 220,
    background: "var(--card-bg)",
    color: "var(--text)",
  },
  loginButton: {
    padding: "8px 12px",
    borderRadius: 6,
    border: "none",
    background: "#8b5cf6",
    color: "white",
    cursor: "pointer",
  },
  logoutButton: {
    padding: "8px 12px",
    borderRadius: 6,
    border: "none",
    background: "#ef4444",
    color: "white",
    cursor: "pointer",
  },
  registerButton: {
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    color: "var(--text)",
    cursor: "pointer",
  },
  createButton: {
    padding: "8px 12px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "#8b5cf6",
    color: "white",
    cursor: "pointer",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: "24px 40px",
    maxWidth: 1100,
    margin: "0 auto",
  },
  appShell: {
    fontFamily: "Inter, system-ui, sans-serif",
    color: "var(--text)",
    minHeight: "100vh",
    padding: 24,
    background:
      "radial-gradient(circle at top right, rgba(244,63,94,0.25), transparent 55%), linear-gradient(180deg, rgba(30,41,59,0.95), rgba(15,23,42,0.98))",
  },
  appSurface: {
    borderRadius: 18,
    padding: 20,
    background: "rgba(15,23,42,0.65)",
    border: "1px solid rgba(255,255,255,0.08)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    boxShadow: "0 24px 60px rgba(0,0,0,0.35)",
  },
  storeLayout: {
    display: "grid",
    gridTemplateColumns: "240px 1fr",
    gap: 20,
    marginTop: 18,
  },
  storeSidebar: {
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  storeContent: {
    minWidth: 0,
  },
  sidebarSection: {
    padding: 14,
    borderRadius: 12,
    background: "rgba(15,23,42,0.75)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  sidebarTitle: {
    fontWeight: 700,
    fontSize: 13,
    color: "#f8fafc",
    letterSpacing: 0.3,
  },
  sidebarList: {
    display: "grid",
    gap: 8,
  },
  sidebarItem: {
    padding: "8px 10px",
    borderRadius: 8,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(30,41,59,0.6)",
    color: "#e2e8f0",
    textAlign: "left",
    cursor: "pointer",
  },
  bannerCard: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 16,
    padding: 20,
    borderRadius: 16,
    background: "linear-gradient(120deg, rgba(248,113,113,0.25), rgba(56,189,248,0.2))",
    border: "1px solid rgba(255,255,255,0.12)",
  },
  bannerTitle: {
    fontSize: 24,
    fontWeight: 700,
  },
  bannerSubtitle: {
    marginTop: 8,
    color: "var(--muted)",
  },
  bannerButton: {
    marginTop: 12,
    padding: "10px 14px",
    borderRadius: 999,
    border: "none",
    background: "#f43f5e",
    color: "white",
    cursor: "pointer",
  },
  bannerArt: {
    width: 180,
    height: 120,
    borderRadius: 14,
    background: "linear-gradient(135deg,#f97316,#ec4899)",
    boxShadow: "0 16px 40px rgba(0,0,0,0.25)",
  },
  updatesList: {
    display: "grid",
    gap: 12,
  },
  updateRow: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    padding: 12,
    borderRadius: 12,
    background: "rgba(30,41,59,0.55)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  updateIcon: {
    width: 44,
    height: 44,
    borderRadius: 12,
    background: "linear-gradient(135deg,#60a5fa,#a78bfa)",
  },
  updateMeta: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  updateTags: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
  },
  tagPill: {
    fontSize: 11,
    padding: "4px 8px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.08)",
    color: "#e2e8f0",
  },
  updateButton: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#f8fafc",
    textDecoration: "none",
  },
  flipContainer: {
    perspective: "1000px",
    cursor: "pointer",
    display: "block",
    position: "relative",
    minHeight: 200,
    overflow: "visible",
  },
  flipper: {
    position: "relative",
    transformStyle: "preserve-3d",
    transition: "transform 0.6s",
  },
  front: {
    backfaceVisibility: "hidden",
    position: "relative",
    zIndex: 2,
  },
  back: {
    transform: "rotateY(180deg)",
    backfaceVisibility: "hidden",
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: "100%",
  },
  card: {
    padding: 16,
    borderRadius: 8,
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
    minHeight: 180,
    cursor: "pointer",
    width: "100%",
    color: "var(--text)",
  },
  preferencesPanel: {
    marginTop: 18,
    marginBottom: 16,
    padding: 16,
    border: "1px solid var(--border)",
    borderRadius: 10,
    background: "var(--card-bg)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  themeChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  themeChip: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    cursor: "pointer",
    fontSize: 14,
  },
  customThemeRow: {
    display: "flex",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  themeInput: {
    padding: "8px 10px",
    borderRadius: 6,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    color: "var(--text)",
    width: "100%",
    maxWidth: 220,
  },
  addThemeButton: {
    padding: "8px 12px",
    borderRadius: 6,
    border: "none",
    background: "#8b5cf6",
    color: "white",
    cursor: "pointer",
  },
  notificationWrapper: {
    position: "relative",
    display: "inline-block",
  },
  notificationBadge: {
    marginLeft: 6,
    background: "#ef4444",
    color: "white",
    borderRadius: 999,
    padding: "0 6px",
    fontSize: 12,
  },
  notificationDropdown: {
    position: "absolute",
    top: "110%",
    right: 0,
    width: 260,
    maxHeight: 320,
    overflowY: "auto",
    background: "var(--card-bg)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 10,
    boxShadow: "0 4px 16px rgba(0,0,0,0.12)",
    zIndex: 20,
  },
  notificationItem: {
    padding: "6px 0",
    borderBottom: "1px solid var(--border)",
  },
  pillButton: {
    padding: "6px 10px",
    borderRadius: 999,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    color: "var(--text)",
    cursor: "pointer",
    fontSize: 13,
  },
  formCard: {
    padding: 20,
    borderRadius: 16,
    background: "rgba(15,23,42,0.65)",
    border: "1px solid rgba(255,255,255,0.08)",
    boxShadow: "0 16px 40px rgba(0,0,0,0.25)",
  },
  panelCard: {
    padding: 16,
    borderRadius: 12,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    boxShadow: "0 1px 3px rgba(0,0,0,0.08)",
  },
  textInput: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    color: "var(--text)",
  },
  textArea: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--card-bg)",
    color: "var(--text)",
    resize: "vertical",
  },
  pageTitle: {
    margin: 0,
    fontSize: 24,
    fontWeight: 700,
  },
  sectionTitle: {
    margin: "0 0 8px 0",
    fontSize: 16,
    fontWeight: 600,
  },
  mutedText: {
    color: "var(--muted)",
  },
  link: {
    color: "#3b82f6",
  },
};
